title: John B-R's Coding
description: A place to show what I have done.

theme: jekyll-theme-slate


# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  internal: true
  url: ./
- text: About
  internal: true
  url: about.md
